# Generated by Django 4.2.3 on 2023-08-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.discounts')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.types')),
            ],
        ),
    ]
