# Generated by Django 4.2.3 on 2023-08-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('test_require', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='Course_Type',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='course_type',
        ),
        migrations.RenameField(
            model_name='course_type',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_start',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.subject'),
        ),
    ]
