# Generated by Django 4.2.3 on 2023-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_rename_type_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
