# Generated by Django 4.2.3 on 2023-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_discount_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.FloatField(null=True),
        ),
    ]
