# Generated by Django 4.2.3 on 2023-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_discount_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
