# Generated by Django 4.2.3 on 2023-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_discount_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule_start',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_day',
            field=models.DateTimeField(default=None),
        ),
    ]
