# Generated by Django 4.2.3 on 2023-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_schedule_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='schedule_day',
            new_name='schedule_end',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_start',
            field=models.DateTimeField(default=None),
        ),
    ]
