# Generated by Django 4.2.3 on 2023-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_schedule_day_course_schedule_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule_days',
            field=models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default=None, max_length=20),
        ),
    ]
