# Generated by Django 4.2.3 on 2023-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_schedule_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default=None, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule_days',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_days',
            field=models.ManyToManyField(to='courses.days'),
        ),
    ]
